/*
    Copyright (C) 1995-2013, The AROS Development Team. All rights reserved.
*/

#include <ctype.h>

static const unsigned short int __ctype_b_array[256] =
{
    _IScntrl, /* 0 */
    _IScntrl, /* 1 */
    _IScntrl, /* 2 */
    _IScntrl, /* 3 */
    _IScntrl, /* 4 */
    _IScntrl, /* 5 */
    _IScntrl, /* 6 */
    _IScntrl, /* 7 */
    _IScntrl, /* Backspace */
    _ISblank|_IScntrl|_ISspace, /* 9 */
    _IScntrl|_ISspace, /* LF */
    _IScntrl|_ISspace, /* 11 */
    _IScntrl|_ISspace, /* 12 */
    _IScntrl|_ISspace, /* CR */
    _IScntrl, /* 14 */
    _IScntrl, /* 15 */
    _IScntrl, /* 16 */
    _IScntrl, /* 17 */
    _IScntrl, /* 18 */
    _IScntrl, /* 19 */
    _IScntrl, /* 20 */
    _IScntrl, /* 21 */
    _IScntrl, /* 22 */
    _IScntrl, /* 23 */
    _IScntrl, /* 24 */
    _IScntrl, /* 25 */
    _IScntrl, /* 26 */
    _IScntrl, /* ESC */
    _IScntrl, /* 28 */
    _IScntrl, /* 29 */
    _IScntrl, /* 30 */
    _IScntrl, /* 31 */
    _ISblank|_ISprint|_ISspace, /* Space */
    _ISgraph|_ISprint|_ISpunct, /* ! */
    _ISgraph|_ISprint|_ISpunct, /* " */
    _ISgraph|_ISprint|_ISpunct, /* # */
    _ISgraph|_ISprint|_ISpunct, /* $ */
    _ISgraph|_ISprint|_ISpunct, /* % */
    _ISgraph|_ISprint|_ISpunct, /* & */
    _ISgraph|_ISprint|_ISpunct, /* ' */
    _ISgraph|_ISprint|_ISpunct, /* ( */
    _ISgraph|_ISprint|_ISpunct, /* ) */
    _ISgraph|_ISprint|_ISpunct, /* * */
    _ISgraph|_ISprint|_ISpunct, /* + */
    _ISgraph|_ISprint|_ISpunct, /* , */
    _ISgraph|_ISprint|_ISpunct, /* - */
    _ISgraph|_ISprint|_ISpunct, /* . */
    _ISgraph|_ISprint|_ISpunct, /* / */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 0 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 1 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 2 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 3 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 4 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 5 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 6 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 7 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 8 */
    _ISdigit|_ISgraph|_ISprint|_ISxdigit, /* 9 */
    _ISgraph|_ISprint|_ISpunct, /* : */
    _ISgraph|_ISprint|_ISpunct, /* ; */
    _ISgraph|_ISprint|_ISpunct, /* < */
    _ISgraph|_ISprint|_ISpunct, /* = */
    _ISgraph|_ISprint|_ISpunct, /* > */
    _ISgraph|_ISprint|_ISpunct, /* ? */
    _ISgraph|_ISprint|_ISpunct, /* @ */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* A */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* B */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* C */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* D */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* E */
    _ISupper|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* F */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* G */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* H */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* I */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* J */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* K */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* L */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* M */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* N */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* O */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* P */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* Q */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* R */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* S */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* T */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* U */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* V */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* W */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* X */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* Y */
    _ISupper|_ISalpha|_ISgraph|_ISprint, /* Z */
    _ISgraph|_ISprint|_ISpunct, /* [ */
    _ISgraph|_ISprint|_ISpunct, /* \ */
    _ISgraph|_ISprint|_ISpunct, /* ] */
    _ISgraph|_ISprint|_ISpunct, /* ^ */
    _ISgraph|_ISprint|_ISpunct, /* _ */
    _ISgraph|_ISprint|_ISpunct, /* ` */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* a */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* b */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* c */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* d */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* e */
    _ISlower|_ISalpha|_ISgraph|_ISprint|_ISxdigit, /* f */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* g */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* h */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* i */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* j */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* k */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* l */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* m */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* n */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* o */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* p */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* q */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* r */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* s */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* t */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* u */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* v */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* w */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* x */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* y */
    _ISlower|_ISalpha|_ISgraph|_ISprint, /* z */
    _ISgraph|_ISprint|_ISpunct, /* { */
    _ISgraph|_ISprint|_ISpunct, /* | */
    _ISgraph|_ISprint|_ISpunct, /* } */
    _ISgraph|_ISprint|_ISpunct, /* ~ */
    _IScntrl, /* Del */
    0, /* 128 */
    0, /* 129 */
    0, /* 130 */
    0, /* 131 */
    0, /* 132 */
    0, /* 133 */
    0, /* 134 */
    0, /* 135 */
    0, /* 136 */
    0, /* 137 */
    0, /* 138 */
    0, /* 139 */
    0, /* 140 */
    0, /* 141 */
    0, /* 142 */
    0, /* 143 */
    0, /* 144 */
    0, /* 145 */
    0, /* 146 */
    0, /* 147 */
    0, /* 148 */
    0, /* 149 */
    0, /* 150 */
    0, /* 151 */
    0, /* 152 */
    0, /* 153 */
    0, /* 154 */
    0, /* CSI */
    0, /* 156 */
    0, /* 157 */
    0, /* 158 */
    0, /* 159 */
    0, /* NBSpace */
    0, /* ¡ */
    0, /* ¢ */
    0, /* £ */
    0, /* ¤ */
    0, /* ¥ */
    0, /* ¦ */
    0, /* § */
    0, /* ¨ */
    0, /* © */
    0, /* ª */
    0, /* « */
    0, /* ¬ */
    0, /* ­ */
    0, /* ® */
    0, /* ¯ */
    0, /* ° */
    0, /* ± */
    0, /* ² */
    0, /* ³ */
    0, /* ´ */
    0, /* µ */
    0, /* ¶ */
    0, /* · */
    0, /* ¸ */
    0, /* ¹ */
    0, /* º */
    0, /* » */
    0, /* ¼ */
    0, /* ½ */
    0, /* ¾ */
    0, /* ¿ */
    0, /* À */
    0, /* Á */
    0, /* Â */
    0, /* Ã */
    0, /* Ä */
    0, /* Å */
    0, /* Æ */
    0, /* Ç */
    0, /* È */
    0, /* É */
    0, /* Ê */
    0, /* Ë */
    0, /* Ì */
    0, /* Í */
    0, /* Î */
    0, /* Ï */
    0, /* Ð */
    0, /* Ñ */
    0, /* Ò */
    0, /* Ó */
    0, /* Ô */
    0, /* Õ */
    0, /* Ö */
    0, /* × */
    0, /* Ø */
    0, /* Ù */
    0, /* Ú */
    0, /* Û */
    0, /* Ü */
    0, /* Ý */
    0, /* Þ */
    0, /* ß */
    0, /* à */
    0, /* á */
    0, /* â */
    0, /* ã */
    0, /* ä */
    0, /* å */
    0, /* æ */
    0, /* ç */
    0, /* è */
    0, /* é */
    0, /* ê */
    0, /* ë */
    0, /* ì */
    0, /* í */
    0, /* î */
    0, /* ï */
    0, /* ð */
    0, /* ñ */
    0, /* ò */
    0, /* ó */
    0, /* ô */
    0, /* õ */
    0, /* ö */
    0, /* ÷ */
    0, /* ø */
    0, /* ù */
    0, /* ú */
    0, /* û */
    0, /* ü */
    0, /* ý */
    0, /* þ */
    0, /* ÿ */
};

const unsigned short int * const __ctype_b = &__ctype_b_array[0];

const unsigned short int * const * const __ctype_b_ptr = &__ctype_b;
